include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_base
  - build
  - test

build base:
  extends: .container-builder-cscs-gh200
  stage: build_base
  before_script:
    - DOCKER_TAG=`cat .cscs/Dockerfile.base | sha256sum - | head -c 16`
    - export PERSIST_IMAGE_NAME=$CSCS_REGISTRY_PATH/base/quatrex:$DOCKER_TAG
    - echo "BASE_IMAGE=$PERSIST_IMAGE_NAME" > build.env
  artifacts:
    reports:
      dotenv: build.env
  variables:
    DOCKERFILE: .cscs/Dockerfile.base

build quatrex:
  extends: .container-builder-cscs-gh200
  stage: build
  variables:
    DOCKERFILE: .cscs/Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/software/quatrex:$CI_COMMIT_SHORT_SHA
    DOCKER_BUILD_ARGS: '["BASE_IMG=$BASE_IMAGE"]'

test quatrex single:
  extends: .container-runner-daint-gh200
  image: $CSCS_REGISTRY_PATH/software/quatrex:$CI_COMMIT_SHORT_SHA
  script:
    - . /opt/venv/bin/activate
    - python3 -c "import numpy; numpy.show_config()"
    - python3 -c "import cupy; cupy.show_config()"
    - cd /opt/repo && ls -alh
    - pytest tests/quatrex/reference
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: '00:30:00'


test quatrex multi:
  extends: .container-runner-daint-gh200
  image: $CSCS_REGISTRY_PATH/software/quatrex:$CI_COMMIT_SHORT_SHA
  script:
    - . /opt/venv/bin/activate
    - python3 -c "import numpy; numpy.show_config()"
    - python3 -c "import cupy; cupy.show_config()"
    - cd /opt/repo && ls -alh
    - pytest tests/qttools --only-mpi -n 0
  variables:
    SLURM_JOB_NUM_NODES: 2
    SLURM_NTASKS: 6
    CUDA_VISIBLE_DEVICES: $SLURM_LOCALID
    SLURM_TIMELIMIT: '00:30:00'

