FROM jfrog.svc.cscs.ch/dockerhub/nvidia/cuda:12.8.1-devel-ubuntu24.04

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

ARG libfabric_version=2.4.0
ARG mpi_version=4.3.1

# workaround ubuntu ports slowing us down
RUN sed -i -e 's|http://archive.ubuntu.com/ubuntu|https://jfrog.svc.cscs.ch/artifactory/ubuntu|' -e 's|http://security.ubuntu.com/ubuntu|https://jfrog.svc.cscs.ch/artifactory/ubuntu|' -e 's|http://ports.ubuntu.com/ubuntu-ports|https://jfrog.svc.cscs.ch/artifactory/ubuntu-ports|' /etc/apt/sources.list.d/ubuntu.sources \
    && printf '%s\n%s' "Acquire::http::AllowRedirect "true";" "Acquire::http::Pipeline-Depth "0";" > /etc/apt/apt.conf.d/99-jfrog-proxy \
    && apt -o "Acquire::https::Verify-Peer=false" update \
    && apt -o "Acquire::https::Verify-Peer=false" install ca-certificates

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    automake \
    autoconf \
    libtool \
    make \
    cmake \
    libblas-dev \
    liblapack-dev \
    gdb \
    strace \
    wget \
    python3.13 \
    python3.13-venv \
    python3.13-dev \
    git \
    git-lfs \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

# When building on a machine without a GPU, during the build process on
# Daint the GPU driver and libraries are not imported into the build
# process
RUN echo '/usr/local/cuda/lib64/stubs' > /etc/ld.so.conf.d/cuda_stubs.conf && ldconfig


RUN git clone https://github.com/hpc/xpmem \
    && cd xpmem/lib \
    && gcc -I../include -shared -o libxpmem.so.1 libxpmem.c \
    && ln -s libxpmem.so.1 libxpmem.so \
    && mv libxpmem.so* /usr/lib \
    && cp ../include/xpmem.h /usr/include/ \
    && ldconfig \
    && cd ../../ \
    && rm -Rf xpmem

RUN wget -q https://github.com/ofiwg/libfabric/archive/v${libfabric_version}.tar.gz \
    && tar xf v${libfabric_version}.tar.gz \
    && cd libfabric-${libfabric_version} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf v${libfabric_version}.tar.gz libfabric-${libfabric_version}

RUN wget -q https://www.mpich.org/static/downloads/${mpi_version}/mpich-${mpi_version}.tar.gz \
    && tar xf mpich-${mpi_version}.tar.gz \
    && cd mpich-${mpi_version} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --enable-fast=O3,ndebug --enable-fortran --enable-cxx --with-device=ch4:ofi --with-libfabric=/usr --with-xpmem=/usr --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-${mpi_version}.tar.gz mpich-${mpi_version}

# Make python3.13 the default python3.
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1 \
    && python3 -m ensurepip --upgrade

# Install cuDSS and build a commlayer for it.
RUN wget https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-sbsa/libcudss-linux-sbsa-0.8.0.10_cuda12-archive.tar.xz \
    && tar -xf libcudss-linux-sbsa-0.8.0.10_cuda12-archive.tar.xz \
    && cp -a libcudss-linux-sbsa-0.8.0.10_cuda12-archive/lib/libcudss.* /usr/local/lib/ \
    && cp -a libcudss-linux-sbsa-0.8.0.10_cuda12-archive/include/. /usr/local/include/ \
    && cd libcudss-linux-sbsa-0.8.0.10_cuda12-archive/src \
    # Not actually OpenMPI, but the build script expects it to be called that way.
    && CUDA_PATH=/usr/local/cuda CUDSS_PATH=./.. MPI_PATH=/usr/local/mpich source ./cudss_build_commlayer.sh openmpi \
    && mv cudss_commlayer_openmpi.so /usr/local/lib \
    && ldconfig \
    && cd ../.. \
    && rm -rf libcudss-linux-sbsa-0.8.0.10_cuda12-archive libcudss-linux-sbsa-0.8.0.10_cuda12-archive.tar.xz

ENV CUDSS_COMM_LIB=/usr/local/lib/cudss_commlayer_openmpi.so

# Install Python dependencies.
RUN python3 -m venv /opt/venv \
    && . /opt/venv/bin/activate \
    && python3 -m pip install numpy scipy h5py \
    && python3 -m pip install --no-binary=mpi4py mpi4py \
    && python3 -m pip install cupy-cuda12x \
    && python3 -m pip install numba pydantic matplotlib threadpoolctl typer \
    && python3 -m pip install pytest pytest-mpi pytest-cov pytest-xdist \
    && python3 -m pip install nvmath-python \
    && python3 -m pip install ase meshio scikit-fem pyvista

# Get rid of the stubs libraries, because at runtime the CUDA driver and
# libraries will be available
RUN rm /etc/ld.so.conf.d/cuda_stubs.conf && ldconfig

# Install Gmsh from source
# as pip does not have a wheel for aarch64
# other option would be to install from conda-forge
RUN git clone https://gitlab.onelab.info/gmsh/gmsh.git \
    && mkdir gmsh/build \
    && cd gmsh/build \
    && cmake -DCMAKE_BUILD_TYPE=Release \
             -DENABLE_BUILD_SHARED=ON \
             -DENABLE_BUILD_DYNAMIC=ON \
             -DENABLE_FLTK=OFF \
             -DENABLE_GRAPHICS=OFF \
             .. \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd / \
    && rm -rf gmsh

# Formalize the Gmsh Python installation so Pip registers it in the venv
RUN mkdir -p dummy_gmsh \
    && cd dummy_gmsh \
    && cp /usr/local/lib/gmsh.py . \
    && printf "from setuptools import setup\nsetup(name='gmsh', version='4.13.1', py_modules=['gmsh'])\n" > setup.py \
    && . /opt/venv/bin/activate \
    && python3 -m pip install . \
    && cd / \
    && rm -rf dummy_gmsh
