simulation_dir = "."
input_dir = "/usr/scratch/mont-fort11/awinka/for_cal/hBN/inputs"
output_dir = "./outputs_hBN"

formalism = "negf" # "negf" or "wf"

[device]
structure_file = "lattice.xyz"
transport_direction = "x"
construct_from_unit_cell = true
num_transport_cells = 3
neighbor_cell_cutoff = [2, 2, 0]
kpoint_grid = [1, 1, 1]
kpoint_shift = [0.0, 0.0, 0.0]
orthogonal_basis = true

[scba] # ===============================================================
max_iterations = 2
mixing_factor = 0.5  # Reduced to dampen oscillations

coulomb_screening = true  # Re-enabled with lower mixing factor
phonon = true

symmetric = true

[outputs] # Select which outputs to write.
electron_ldos = true
contact_currents = false
device_currents = false
electron_density = true
hole_density = true

polarization_density = true
coulomb_screening_density = true

self_energy_density = true

# If enabled, the profiling stats will take a bit of time to crunch the
# numbers.
save_profiling_results = true


[electron] # ===========================================================
fermi_level = -1.75 # eV
left_fermi_level = -1.75 # eV
right_fermi_level = -1.75 # eV
flatband = false

conduction_band_edge = 0.5 # eV 
valence_band_edge = -3.9   # eV
band_edge_tracking = "eigenvalues"

# Energy grid.
energy_window_min = -14
energy_window_max = 12
energy_window_num = 1001

solver.algorithm = "rgf"
solver.max_batch_size = 1000
solver.compute_current = false

obc.algorithm = "spectral"
obc.nevp_solver = "full"
obc.block_sections = 2

# Parameters for Beyn's method.
obc.num_ref_iterations = 2
obc.max_decay = 15
obc.min_decay = 1e-3
obc.r_o = 10
obc.r_i = 0.8
obc.m_0 = 31
obc.num_quad_points = 31

obc.memoizer.mode = "off"
obc.memoizer.num_ref_iterations = 3
obc.memoizer.relative_tol = 1e-2
obc.memoizer.absolute_tol = 1e-8
obc.residual_tolerance = 1e-4

[coulomb_screening] # ==================================================
interaction_cutoff = 8 # Angstrom
epsilon_r = 200
compute_retarded_polarization = true

num_connected_blocks = 1 # Can be 1, 2, 3, or "auto"

solver.algorithm = "rgf"
solver.max_batch_size = 1000

obc.algorithm = "spectral"
obc.nevp_solver = "full"
obc.block_sections = 2

# Parameters for Beyn's method.
obc.num_ref_iterations = 2
obc.max_decay = 15
obc.min_decay = 1e-3
obc.r_o = 10
obc.r_i = 0.8
obc.m_0 = 32
obc.num_quad_points = 31
obc.residual_tolerance = 1e-4

obc.memoizer.mode = "off"
obc.memoizer.num_ref_iterations = 3
obc.memoizer.relative_tol = 1e-2
obc.memoizer.absolute_tol = 1e-8

lyapunov.algorithm = "spectral"

lyapunov.memoizer.mode = "off"
lyapunov.memoizer.num_ref_iterations = 3
lyapunov.memoizer.relative_tol = 2e-1
lyapunov.memoizer.absolute_tol = 1e-6

[phonon]
interaction_cutoff = 5.5     # Å
model = "pseudo-scattering"
phonon_energy = 50e-3
deformation_potential = 5e-3
