name: quatrex-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black>=24.8.0
  - blacken-docs>=1.18.0
  - isort>=5.13.2
  - just>=1.36.0
  - mpi>=1.0.1
  - mpi4py>=4.0.1
  - mpich>=4.2.3
  - numpy>=1.23.2
  - pre-commit>=4.0.1
  - pytest>=8.3.3
  - pydantic>=2.11.7
  - pytest-cov>=6.0.0
  - pytest-mpi>=0.6
  - pytest-xdist>=3.6.1
  - ruff>=0.6.1
  - scipy>=1.14.1
  - setuptools>=75.1.0
  - threadpoolctl>=3.6.0
  - typer>=0.17.4
