[project]
site_name = "quatrex"
site_url = "https://quatrex.github.io/quatrex/"
site_description = "Quantum transport simulations at the exascale and beyond."
copyright = "Copyright &copy; 2024-2026 ETH Zürich and the authors of the quatrex package."

repo_url = "https://github.com/quatrex/quatrex"
repo_name = "quatrex/quatrex"

extra_javascript = [
    "javascript/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]

extra_css = ["stylesheets/custom.css"]

nav = [
    { "Home" = "index.md" },
    { "Getting Started" = [
        { "What is quatrex?" = "getting_started/what_is_quatrex.md" },
        { "Installation" = "getting_started/installation.md" },
        { "Setting up and running a first simulation" = "getting_started/first_simulation.md" },
    ] },
    { "User Guide" = [
        { "Overview" = "user_guide/index.md" },
        { "Introduction" = "user_guide/introduction.md" },
        { "Running Transport Simulations" = [
            { "Command Line Interface" = "user_guide/cli.md" },
            { "Simulation Parameters" = [
                "user_guide/parameters/index.md",
                { "QuaTrEx" = "user_guide/parameters/quatrex.md" },
                { "Device" = "user_guide/parameters/device.md" },
                { "Contact" = "user_guide/parameters/contact.md" },
                { "SCSP" = "user_guide/parameters/scsp.md" },
                { "Poisson" = "user_guide/parameters/poisson.md" },
                { "SCBA" = "user_guide/parameters/scba.md" },
                { "QTBM" = "user_guide/parameters/qtbm.md" },
                { "Electron" = "user_guide/parameters/electron.md" },
                { "Phonon" = "user_guide/parameters/phonon.md" },
                { "Coulomb Screening" = "user_guide/parameters/coulomb_screening.md" },
                { "Photon" = "user_guide/parameters/photon.md" },
                { "OBC" = "user_guide/parameters/obc.md" },
                { "Lyapunov" = "user_guide/parameters/lyapunov.md" },
                { "Memoizer" = "user_guide/parameters/memoizer.md" },
                { "Solver" = "user_guide/parameters/solver.md" },
                { "Output" = "user_guide/parameters/output.md" },
            ] },
        ] },
        { "Examples" = [
            "user_guide/examples/test.md",
        ] },
        { "Methodology" = [
            { "Atomistic Quantum Transport" = "user_guide/methodology/quantum_transport.md" },
            { "Open Boundary Conditions" = "user_guide/methodology/obc.md" },
            { "Quantum Transmitting Boundary Method" = "user_guide/methodology/qtbm.md" },
            { "Non-Equilibrium Green's Functions" = "user_guide/methodology/negf.md" },
            { "Electrostatics" = "user_guide/methodology/electrostatics.md" },
        ] },
    ] },
    { "Contributing" = "contributing.md" },
    # This is a temporary solution while Zensical is currently reworking
    # the automatic generation of navs. Once that is released, we can
    # switch to an automatically generated API reference nav.
    { "API Reference" = [
        { "Overview" = "api/index.md" },
        { "qttools" = [
            "api/qttools/index.md",
            { "boundary_conditions" = [
                "api/qttools/boundary_conditions/index.md",
                { "lyapunov" = [
                    "api/qttools/boundary_conditions/lyapunov/index.md",
                    "api/qttools/boundary_conditions/lyapunov/lyapunov.md",
                    "api/qttools/boundary_conditions/lyapunov/doubling.md",
                    "api/qttools/boundary_conditions/lyapunov/spectral.md",
                ] },
                { "obc" = [
                    "api/qttools/boundary_conditions/obc/index.md",
                    "api/qttools/boundary_conditions/obc/obc.md",
                    "api/qttools/boundary_conditions/obc/sancho_rubio.md",
                    "api/qttools/boundary_conditions/obc/spectral.md",
                ] },
                "api/qttools/boundary_conditions/boundary_system.md",
                "api/qttools/boundary_conditions/system_reduction.md",
            ] },
            { "comm" = [
                "api/qttools/comm/index.md",
                "api/qttools/comm/comm.md",
            ] },
            { "datastructures" = [
                "api/qttools/datastructures/index.md",
                "api/qttools/datastructures/dsdbsparse.md",
                "api/qttools/datastructures/dsdbcoo.md",
                "api/qttools/datastructures/dsdbcsr.md",
                "api/qttools/datastructures/routines.md",
            ] },
            { "fft" = [
                "api/qttools/fft/index.md",
                "api/qttools/fft/ffts.md",
                "api/qttools/fft/convolve.md",
            ] },
            { "greens_function_solver" = [
                "api/qttools/greens_function_solver/index.md",
                "api/qttools/greens_function_solver/solver.md",
                "api/qttools/greens_function_solver/rgf.md",
                "api/qttools/greens_function_solver/rgf_dist.md",
                "api/qttools/greens_function_solver/_serinv.md",
                "api/qttools/greens_function_solver/inv.md",
            ] },
            { "nevp" = [
                "api/qttools/nevp/index.md",
                "api/qttools/nevp/nevp.md",
                "api/qttools/nevp/beyn.md",
                "api/qttools/nevp/full.md",
            ] },
            { "profiling" = [
                "api/qttools/profiling/index.md",
                "api/qttools/profiling/profiler.md",
            ] },
            { "toeplitz" = [
                "api/qttools/toeplitz/index.md",
                "api/qttools/toeplitz/toeplitz.md",
            ] },
            { "utils" = [
                "api/qttools/utils/index.md",
                "api/qttools/utils/solvers_utils.md",
                "api/qttools/utils/gpu_utils.md",
                "api/qttools/utils/hdf5_utils.md",
                "api/qttools/utils/mpi_utils.md",
                "api/qttools/utils/sparse_utils.md",
                "api/qttools/utils/inplace_utils.md",
                "api/qttools/utils/stack_utils.md",
            ] },
            { "wave_function_solver" = [
                "api/qttools/wave_function_solver/index.md",
                "api/qttools/wave_function_solver/superlu.md",
                "api/qttools/wave_function_solver/cudss.md",
                "api/qttools/wave_function_solver/mumps.md",
                "api/qttools/wave_function_solver/solver.md",
            ] },

        ] },
        { "quatrex" = [
            "api/quatrex/index.md",
            { "bandstructure" = [
                "api/quatrex/bandstructure/index.md",
                "api/quatrex/bandstructure/contact.md",
                "api/quatrex/bandstructure/band_edges.md",
            ] },
            { "core" = [
                "api/quatrex/core/index.md",
                "api/quatrex/core/scba.md",
                "api/quatrex/core/qtbm.md",
                "api/quatrex/core/observables.md",
                "api/quatrex/core/utils.md",
                "api/quatrex/core/constants.md",
                "api/quatrex/core/sse.md",
                "api/quatrex/core/statistics.md",
                "api/quatrex/core/subsystem.md",
            ] },
            { "coulomb_screening" = [
                "api/quatrex/coulomb_screening/index.md",
                "api/quatrex/coulomb_screening/solver.md",
                "api/quatrex/coulomb_screening/polarization.md",
            ] },
            { "device" = [
                "api/quatrex/device/index.md",
                "api/quatrex/device/device.md",
                "api/quatrex/device/inputs.md",
                "api/quatrex/device/contact.md",
            ] },
            { "electron" = [
                "api/quatrex/electron/index.md",
                "api/quatrex/electron/sse_photon.md",
                "api/quatrex/electron/solver.md",
                "api/quatrex/electron/sse_coulomb_screening.md",
                "api/quatrex/electron/sse_fock.md",
                "api/quatrex/electron/sse_phonon.md",
            ] },
            { "grid" = [
                "api/quatrex/grid/index.md",
                "api/quatrex/grid/energies.md",
                "api/quatrex/grid/kpoints.md",
            ] },
            { "phonon" = [
                "api/quatrex/phonon/index.md",
                "api/quatrex/phonon/polarization.md",
                "api/quatrex/phonon/solver.md",
            ] },
            { "photon" = [
                "api/quatrex/photon/index.md",
                "api/quatrex/photon/solver.md",
                "api/quatrex/photon/polarization.md",
            ] },
            { "post_processing" = [
                "api/quatrex/post_processing/index.md",
                "api/quatrex/post_processing/plot_ldos.md",
            ] },
        ] },
    ] },
]


    [project.theme]
    variant = "modern"
    font.text = "Inter"
    font.code = "Fira Code"

    icon.repo = "fontawesome/brands/github"

    features = [
        "navigation.footer",
        "navigation.indexes",
        "navigation.sections",
        "navigation.tabs",
        "navigation.top",
        "navigation.tracking",
        "content.code.copy",
    ]


        [[project.theme.palette]]
        media = "(prefers-color-scheme)"
        primary = "white"
        toggle.icon = "lucide/sun-moon"
        toggle.name = "Switch to light mode"

        [[project.theme.palette]]
        media = "(prefers-color-scheme: light)"
        primary = "white"
        scheme = "default"
        toggle.icon = "lucide/sun"
        toggle.name = "Switch to dark mode"

        [[project.theme.palette]]
        media = "(prefers-color-scheme: dark)"
        primary = "white"
        scheme = "slate"
        toggle.icon = "lucide/moon"
        toggle.name = "Switch to system preference"


    [project.markdown_extensions.abbr]
    [project.markdown_extensions.admonition]
    [project.markdown_extensions.attr_list]
    [project.markdown_extensions.def_list]
    [project.markdown_extensions.footnotes]
    [project.markdown_extensions.md_in_html]
    [project.markdown_extensions.toc]
    permalink = "#"
    [project.markdown_extensions.pymdownx.arithmatex]
    generic = true
    [project.markdown_extensions.pymdownx.betterem]
    [project.markdown_extensions.pymdownx.caret]
    [project.markdown_extensions.pymdownx.details]
    [project.markdown_extensions.pymdownx.emoji]
    emoji_generator = "zensical.extensions.emoji.to_svg"
    emoji_index = "zensical.extensions.emoji.twemoji"
    [project.markdown_extensions.pymdownx.highlight]
    anchor_linenums = true
    line_spans = "__span"
    pygments_lang_class = true
    [project.markdown_extensions.pymdownx.inlinehilite]
    [project.markdown_extensions.pymdownx.keys]
    [project.markdown_extensions.pymdownx.magiclink]
    [project.markdown_extensions.pymdownx.mark]
    [project.markdown_extensions.pymdownx.smartsymbols]
    [project.markdown_extensions.pymdownx.superfences]
    custom_fences = [
        { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
    ]
    [project.markdown_extensions.pymdownx.tabbed]
    alternate_style = true
    combine_header_slug = true
    [project.markdown_extensions.tables]
    [project.markdown_extensions.pymdownx.tasklist]
    custom_checkbox = true
    [project.markdown_extensions.pymdownx.tilde]


    [project.plugins.mkdocstrings.handlers.python]
    inventories = [
        "https://docs.python.org/3/objects.inv",
        "https://docs.scipy.org/doc/scipy/objects.inv",
        "https://numpy.org/doc/stable/objects.inv",
        "https://docs.cupy.dev/en/stable/objects.inv",
    ]
    paths = ["src"]

        [project.plugins.mkdocstrings.handlers.python.options]
        docstring_style = "numpy"
        docstring_options.ignore_init_summary = true
        docstring_section_style = "list"
        signature_crossrefs = true
        summary = true
        parameter_headings = false
        show_symbol_type_heading = true
        show_symbol_type_toc = true
        line_length = 88
        show_source = false
        merge_init_into_class = true
        separate_signature = true
        show_signature_annotations = true
        members_order = "source"
