simulation_dir = "."

formalism = "qtbm" # "negf" or "qtbm"

[device]
transport_direction = "x"
kpoint_grid = [1, 1, 1]
num_orbitals_per_atom = { "C" = 3 }
particle_type='boson'

    [[device.contacts]]
    name = "left"
    origin = [0.012479, 0.0, 0.0]
    size = [[4.27615261, 0, 0], [0, 50, 0], [0, 0, 50]]
    direction = "a"
    temperature=301

    [[device.contacts]]
    name = "right"
    origin = [102.55062666, 0.0, 0.0]
    size = [[-4.27615261, 0, 0], [0, 50, 0], [0, 0, 50]]
    direction = "a"
    temperature=300

[qtbm] # ===============================================================
max_batch_size = 2000


[outputs] # Select which outputs to write.
electron_ldos = true
contact_currents = true
device_currents = true
electron_density = true
hole_density = true


[electron] # ===========================================================
# 0.2 V Potential difference.
left_fermi_level = 0.0  # eV
right_fermi_level = 0.0 # eV

# Energy grid.
energy_window_min = 4e-5
energy_window_max = 0.2018
energy_window_num = 1010

solver.direct_solver = "cudss"

obc.algorithm = "spectral"
obc.nevp_solver = "beyn"

# Parameters for Beyn's method.
obc.num_ref_iterations = 3
obc.max_decay = 15
obc.min_decay = 1e-8
obc.r_o = 1.1
obc.r_i = 0.9
obc.m_0 = 93
obc.num_quad_points = 64

obc.residual_tolerance = 1e-4
