# Copyright (c) 2025 ETH Zurich and the authors of the quatrex package.

# This file contains a manifest of example datasets. Each dataset has a
# name, a URL to download it from, and an optional SHA256 checksum to
# verify the integrity of the downloaded file.

[carbon-nanotube-hamiltonian]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/hamiltonian.npz"
sha256 = "a49650281d17c28276cb1220903edf6cf6c879d8b4ed5fe0cce0d615f5f01477"

# TODO: remove ref to PR branch once merged in huggingface
[carbon-nanotube-coulomb-matrix]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/coulomb_matrix.npz"
sha256 = "f07f1884afb83e16f5eaee4cd52e606852c93d157762f2ab7d9cf1723527a6d5"

[carbon-nanotube-potential]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/potential.npy"
sha256 = "91b0f3e7dc80cc0f6fdc11d5bb0a20c0d1a27621581bb09162d0caabda9818e5"

[carbon-nanotube-grid]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/grid.npy"
sha256 = "66f976b634732a38077e1db5aa69f72ed0c9ec4d4a4b55a051c1ef96a7d162b9"

[carbon-nanotube-block-sizes]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/block_sizes.npy"
sha256 = "5ae34aa4479a9b2154b14e677ae8ba6ec4814c3b724b610f2ab5f422fa4ad49f"

[carbon-nanotube-i_meir-wingreen_1-]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/i_meir-wingreen_1_.npy"
sha256 = "9a6e102793df4a569ddc0920f355db590dc062e032490f32f2a8b4c669927df0"

[carbon-nanotube-electron_ldos_1-]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/electron_ldos_1_.npy"
sha256 = "5b11a621825308d3c3b42631754c49387fb8a41c363e82bc8f89ca77a4de886d"

[carbon-nanotube-electron_density_1-dist]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/electron_density_1_dist.npy"
sha256 = "d0ee24232b309d528b55174044014e1f777efcdcd8fd9d8de5e14aafe843abbf"

[carbon-nanotube-i_device_1-dist]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/refs%2Fpr%2F4/quantum_transport/cnt_w90/i_device_1_dist.npy"
sha256 = "a863ca38cdde927a424bde78342cd8805f85cf2d2a7147131a0223b06a2bd488"


[silicon-nanowire]
url = "https://huggingface.co/datasets/vincent-maillou/NEST/resolve/main/quantum_transport/sinw_w90/sinw_w90.npz"
sha256 = "7e9608d54b3ae97b6629a7bb8e1728db0bf455b8002a854efff34b9a2507cdc5"

[cp2k-atomic-chain-hamiltonian_0_0_0]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/inputs/hamiltonian_0_0_0.npz"
sha256 = "0f9589074442b31cce681d877c2df54cefe348416673513263ccaf1e0feea9f6"

[cp2k-atomic-chain-lattice]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/inputs/lattice.xyz"
sha256 = "d120dc1500f1ab6be61e5aff424f3f31fa2ffc4326b904cf81608f7ff0eab4ec"

[cp2k-atomic-chain-potential]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/inputs/potential.npy"
sha256 = "7915aced6d1611d860fd5b2a8853f8ec7499b446f458baa34970876404936e7c"

[cp2k-atomic-chain-overlap_0_0_0]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/inputs/overlap_0_0_0.npz"
sha256 = "f84400d6bd7958f03ffce8d4966dba56e3b1745984d83573f3118dd86168c37f"

[cp2k-atomic-chain-dos_l-qtbm]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/outputs/dos_l_qtbm.npy"
sha256 = "b5e5a7dd01e8c8c84ed984e5bfe87b0e6b8e6949b272d3dbbc8f8e1fbdba9dcd"

[cp2k-atomic-chain-dos_r-qtbm]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/outputs/dos_r_qtbm.npy"
sha256 = "2d70e45e07a2affab0efb978ff0a10cb11e8a6a4124009616f4a495bf9b97ccf"

[cp2k-atomic-chain-transmission_lr-qtbm]
url = "https://github.com/quatrex/quatrex-examples/raw/refs/heads/qtbm_examples/cp2k/atomic-chain/outputs/transmission_lr_qtbm.npy"
sha256 = "2a8603969b2e4611803bc31c493abb4efeaea5f7695da1fd4f550ac9998082d0"
