simulation_dir = "."
input_dir = "../inputs"

formalism = "wf"

[qtbm]
max_batch_size = 1
[device]
transport_direction = 'x'
num_orbitals_per_atom = {"C"=13}
kpoint_grid = [1,1,1]
kpoint_shift = [0,0,0]

    [[device.contacts]]
    name = "left"
    origin = [0.65, 0 ,0]
    lattice_vectors = [[2.57031, 0, 0], [0,10 , 0], [0, 0, 10]]
    direction = "a"
     fermi_level = -3

    [[device.contacts]]
    name = "right"
    origin = [256.4,  -0.001 ,-0.001]
    lattice_vectors = [[-2.57031 , 0, 0], [0, 10 , 0], [0, 0, 10]]
    direction = "a"
    fermi_level = -3.001


[electron]
    conduction_band_edge = -2.4
    valence_band_edge = -2.5

    energy_window_min = -5
    energy_window_max = -4
    energy_window_num = 10

    [electron.obc]
    algorithm = "spectral"
    num_ref_iterations = 10
    nevp_solver = "full"
    r_o = 1000
    r_i = 0.9
    m_0 = 100
    num_quad_points = 64
    min_decay = 1e-8
    max_decay = 10
