simulation_dir = "."
input_dir = "../inputs"

formalism = "negf" # "negf" or "wf"

[device]
transport_direction = 'x'
block_size = 32

[scba] # ===============================================================
max_iterations = 2
mixing_factor = 1

phonon = true

symmetric = true

[outputs] # Select which outputs to write.
electron_ldos = true
device_currents = true
electron_density = false
hole_density = false

self_energy_density = true

# If enabled, the profiling stats will take a bit of time to crunch the
# numbers.
save_profiling_results = true


[electron] # ===========================================================
left_contact.name = "source"
left_contact.fermi_level = -3.6  # eV

right_contact.name = "drain"
right_contact.fermi_level = -3.6  # eV

# Energy grid.
energy_window_min = -5.6
energy_window_max = -1.6
energy_window_num = 100

solver.algorithm = "rgf"
solver.max_batch_size = 1000
solver.compute_current = true # Compute Meir-Wingreen current.

obc.algorithm = "spectral"
obc.nevp_solver = "full"
obc.block_sections = 1

# Parameters for Beyn's method.
obc.num_ref_iterations = 2
obc.max_decay = 15
obc.min_decay = 1e-3

obc.memoizer.mode = "off"

[phonon]
interaction_cutoff = 5.5  # Å
model = "long-wavelength"
temperature = 300  # K
# Deformation potentials are of order 1 eV / 1 eV/Å:
# https://journals.aps.org/prb/abstract/10.1103/PhysRevB.104.195201#s3
acoustic_deformation_potential = 1  # eV
optical_deformation_potential = 1  # eV / Å
# 1.99264688270e-26 kg / (1e-20 / e)
atom_mass = 3.192572275274879e-25  # (eV s^2) / Å^2
