# Copyright 2025 ETH Zurich and Quantum Transport Toolbox authors.
name: Run Basic Tests and Determine Code Coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  test-cov:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Get Git LFS Files
        run: git lfs pull

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.13"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: quatrex-dev
          environment-file: environment-dev.yaml

      - name: Install quatrex without Dependencies
        run: |
          pip install --no-deps --editable .

      - name: Run QTTools MPI Tests
        run: |
          NUMBA_DISABLE_JIT=1 mpiexec -np 6 coverage run --source=src --parallel-mode -m pytest -x --only-mpi tests/qttools

      - name: Run QuaTrEx MPI Tests
        run: |
          NUMBA_DISABLE_JIT=1 mpiexec -np 6 coverage run --source=src --parallel-mode -m pytest -x --only-mpi tests/quatrex

      - name: Run NUMBA Tests (QTTools Kernels)
        if: success() || failure()
        run: |
          coverage run --source=src --parallel-mode -m pytest --with-mpi tests/qttools/kernels

      - name: Run QTTools Tests
        if: success() || failure()
        run: |
          NUMBA_DISABLE_JIT=1 coverage run --source=src --parallel-mode -m pytest --with-mpi tests/qttools
      
      - name: Run QuaTrEx Tests and Determine Coverage
        if: success() || failure()
        run: |
          coverage run --source=src --parallel-mode -m pytest --with-mpi tests/quatrex
          coverage combine .; coverage report; coverage xml
